"""
brand_seed_data.py

Real brand-name -> generic/manufacturer/category/dosage-form data, exactly
as provided by the pharmacist (not generated/guessed - see brand_mapping.py
for why that distinction matters here). Each tuple:
    (brand_name, generic_text, dosage_form, manufacturer, category)

To add more brands later: append tuples here, or use the Brand Master
screen's "Bulk Add (paste from Excel)" box, which parses the same
tab-separated shape you'd copy out of a spreadsheet.
"""

BRANDS = [
    ("Zerodol-P", "Aceclofenac 100mg + Paracetamol 325mg", "Tablet", "Ipca Laboratories Ltd", "Analgesic / Anti-inflammatory"),
    ("Acycloflam", "Aceclofenac 100mg + Paracetamol 325mg", "Tablet", "Cipla Ltd", "Analgesic / Anti-inflammatory"),
    ("Aceclo Plus", "Aceclofenac 100mg + Paracetamol 325mg", "Tablet", "Aristo Pharmaceuticals", "Analgesic / Anti-inflammatory"),
    ("Hifenac-P", "Aceclofenac 100mg + Paracetamol 325mg", "Tablet", "Intas Pharmaceuticals", "Analgesic / Anti-inflammatory"),
    ("Morfen-P", "Aceclofenac 100mg + Paracetamol 325mg", "Tablet", "Micro Labs Ltd", "Analgesic / Anti-inflammatory"),
    ("Dolokind-P", "Aceclofenac 100mg + Paracetamol 325mg", "Tablet", "Mankind Pharma", "Analgesic / Anti-inflammatory"),
    ("Algesia-P", "Aceclofenac 100mg + Paracetamol 325mg", "Tablet", "Alkem Laboratories", "Analgesic / Anti-inflammatory"),
    ("Acrofen-P", "Aceclofenac 100mg + Paracetamol 325mg", "Tablet", "Sun Pharmaceutical", "Analgesic / Anti-inflammatory"),
    ("Signoflam-P", "Aceclofenac 100mg + Paracetamol 325mg", "Tablet", "Lupin Ltd", "Analgesic / Anti-inflammatory"),
    ("Zerolac-P", "Aceclofenac 100mg + Paracetamol 325mg", "Tablet", "Torrent Pharmaceuticals", "Analgesic / Anti-inflammatory"),
    ("Zerodol-SP", "Aceclofenac 100mg + Paracetamol 325mg + Serratiopeptidase 15mg", "Tablet", "Ipca Laboratories Ltd", "Analgesic / Anti-inflammatory"),
    ("Hifenac-D", "Aceclofenac 100mg + Paracetamol 325mg + Serratiopeptidase 15mg", "Tablet", "Intas Pharmaceuticals", "Analgesic / Anti-inflammatory"),
    ("Aldigesic-SP", "Aceclofenac 100mg + Paracetamol 325mg + Serratiopeptidase 15mg", "Tablet", "Alkem Laboratories", "Analgesic / Anti-inflammatory"),
    ("Signoflam", "Aceclofenac 100mg + Paracetamol 325mg + Serratiopeptidase 15mg", "Tablet", "Lupin Ltd", "Analgesic / Anti-inflammatory"),
    ("Dolowin Plus", "Aceclofenac 100mg + Paracetamol 325mg + Serratiopeptidase 15mg", "Tablet", "Micro Labs Ltd", "Analgesic / Anti-inflammatory"),
    ("Dolo 650", "Paracetamol 650mg", "Tablet", "Micro Labs Ltd", "Antipyretic / Analgesic"),
    ("Calpol 650", "Paracetamol 650mg", "Tablet", "GlaxoSmithKline (GSK)", "Antipyretic / Analgesic"),
    ("Pacimol 650", "Paracetamol 650mg", "Tablet", "Ipca Laboratories Ltd", "Antipyretic / Analgesic"),
    ("Crocin 650", "Paracetamol 650mg", "Tablet", "GlaxoSmithKline (GSK)", "Antipyretic / Analgesic"),
    ("Sumo L 650", "Paracetamol 650mg", "Tablet", "Alkem Laboratories", "Antipyretic / Analgesic"),
    ("Paracetamol 250 Syrup", "Paracetamol 250mg / 5ml", "Syrup", "Cipla Ltd", "Antipyretic / Analgesic"),
    ("Calpol Paediatric Syrup", "Paracetamol 120mg / 5ml", "Syrup", "GlaxoSmithKline (GSK)", "Antipyretic / Analgesic"),
    ("Combiflam", "Ibuprofen 400mg + Paracetamol 325mg", "Tablet", "Sanofi India Ltd", "Analgesic / Anti-inflammatory"),
    ("Ibugesic Plus", "Ibuprofen 400mg + Paracetamol 325mg", "Tablet", "Cipla Ltd", "Analgesic / Anti-inflammatory"),
    ("Flexon", "Ibuprofen 400mg + Paracetamol 325mg", "Tablet", "Aristo Pharmaceuticals", "Analgesic / Anti-inflammatory"),
    ("Nise", "Nimesulide 100mg", "Tablet", "Dr. Reddy's Laboratories", "Analgesic / Anti-inflammatory"),
    ("Nise Plus", "Nimesulide 100mg + Paracetamol 325mg", "Tablet", "Dr. Reddy's Laboratories", "Analgesic / Anti-inflammatory"),
    ("Nicip-P", "Nimesulide 100mg + Paracetamol 325mg", "Tablet", "Cipla Ltd", "Analgesic / Anti-inflammatory"),
    ("Amoxil 500", "Amoxicillin 500mg", "Capsule", "GlaxoSmithKline (GSK)", "Antibiotic"),
    ("Mox 500", "Amoxicillin 500mg", "Capsule", "Sun Pharmaceutical", "Antibiotic"),
    ("Novamox 250 DT", "Amoxicillin 250mg", "Dispersible Tablet", "Cipla Ltd", "Antibiotic"),
    ("Augmentin 625 Duo", "Amoxicillin 500mg + Clavulanate 125mg", "Tablet", "GlaxoSmithKline (GSK)", "Antibiotic"),
    ("Moxikind-CV 625", "Amoxicillin 500mg + Clavulanate 125mg", "Tablet", "Mankind Pharma", "Antibiotic"),
    ("Clavam 625", "Amoxicillin 500mg + Clavulanate 125mg", "Tablet", "Alkem Laboratories", "Antibiotic"),
    ("Augmentin Duo Dry Syrup", "Amoxicillin 200mg + Clavulanic Acid 28.5mg / 5ml", "Syrup", "GlaxoSmithKline (GSK)", "Antibiotic"),
    ("Taxim-O 200", "Cefixime 200mg", "Tablet", "Alkem Laboratories", "Antibiotic"),
    ("Zifi 200", "Cefixime 200mg", "Tablet", "FDC Ltd", "Antibiotic"),
    ("Cefolac 200", "Cefixime 200mg", "Tablet", "Macleods Pharmaceuticals", "Antibiotic"),
    ("Mahacef 200", "Cefixime 200mg", "Tablet", "Mankind Pharma", "Antibiotic"),
    ("Pan 40", "Pantoprazole 40mg", "Tablet", "Alkem Laboratories", "Gastrointestinal / Antacid"),
    ("Pantocid 40", "Pantoprazole 40mg", "Tablet", "Sun Pharmaceutical", "Gastrointestinal / Antacid"),
    ("Pantodac 40", "Pantoprazole 40mg", "Tablet", "Zydus Cadila", "Gastrointestinal / Antacid"),
    ("Pan-D", "Pantoprazole 40mg + Domperidone 30mg SR", "Capsule", "Alkem Laboratories", "Gastrointestinal / Antacid"),
    ("Pantocid-D SR", "Pantoprazole 40mg + Domperidone 30mg SR", "Capsule", "Sun Pharmaceutical", "Gastrointestinal / Antacid"),
    ("Pantozol DSR", "Pantoprazole 40mg + Domperidone 30mg SR", "Capsule", "Micro Labs Ltd", "Gastrointestinal / Antacid"),
    ("Pantop-D", "Pantoprazole 40mg + Domperidone 30mg SR", "Capsule", "Aristo Pharmaceuticals", "Gastrointestinal / Antacid"),
    ("Pan Syrup", "Pantoprazole Oral Suspension", "Syrup", "Alkem Laboratories", "Gastrointestinal / Antacid"),
    ("Rantac 150", "Ranitidine 150mg", "Tablet", "JB Chemicals & Pharma", "Gastrointestinal / Antacid"),
    ("Aciloc 150", "Ranitidine 150mg", "Tablet", "Cadila Pharmaceuticals", "Gastrointestinal / Antacid"),
    ("Gelusil MPS Syrup", "Magaldrate 400mg + Simethicone 20mg", "Syrup", "Pfizer India", "Antacid Liquid"),
    ("Digene Syrup", "Magnesium Hydroxide + Simethicone + Aluminum Hydroxide", "Syrup", "Abbott India", "Antacid Liquid"),
    ("Rexcof 100ml", "Chlorpheniramine Maleate + Dextromethorphan Hydrobromide", "Syrup", "Cipla Ltd", "Cough / Respiratory"),
    ("Alcough DX Syrup 60ml", "Dextromethorphan + Phenylephrine + Chlorpheniramine", "Syrup", "Alkem Laboratories", "Cough / Respiratory"),
    ("Alcough Junior Syrup", "Dextromethorphan + Chlorpheniramine Maleate", "Syrup", "Alkem Laboratories", "Cough / Respiratory"),
    ("Alcough Capsule", "Dextromethorphan + Phenylephrine + Chlorpheniramine", "Capsule", "Alkem Laboratories", "Cough / Respiratory"),
    ("Rovibraz Syrup", "Ambroxol + Guaiphenesin + Terbutaline", "Syrup", "Micro Labs Ltd", "Cough / Respiratory"),
    ("Ascoril LS Syrup", "Levosalbutamol + Ambroxol + Guaiphenesin", "Syrup", "Glenmark Pharmaceuticals", "Cough / Respiratory"),
    ("Benadryl Cough Formula", "Diphenhydramine + Ammonium Chloride + Sodium Citrate", "Syrup", "Johnson & Johnson", "Cough / Respiratory"),
    ("Coldact Capsule", "Paracetamol + Phenylephrine + Chlorpheniramine", "Capsule", "Ipca Laboratories Ltd", "Cold & Respiratory"),
    ("Montair LC", "Montelukast 10mg + Levocetirizine 5mg", "Tablet", "Cipla Ltd", "Anti-allergic / Asthma"),
    ("Monticope", "Montelukast 10mg + Levocetirizine 5mg", "Tablet", "Mankind Pharma", "Anti-allergic / Asthma"),
    ("Montokast-L", "Montelukast 10mg + Levocetirizine 5mg", "Tablet", "Micro Labs Ltd", "Anti-allergic / Asthma"),
    ("Montokast-L Junior", "Montelukast 4mg + Levocetirizine 2.5mg", "Dispersible Tablet", "Micro Labs Ltd", "Anti-allergic / Asthma"),
    ("Montek LC Kid Syrup", "Montelukast 4mg + Levocetirizine 2.5mg / 5ml", "Syrup", "Sun Pharmaceutical", "Anti-allergic / Asthma"),
    ("Cetzine 10", "Cetirizine Hydrochloride 10mg", "Tablet", "Dr. Reddy's Laboratories", "Anti-allergic"),
    ("Alerid 10", "Cetirizine Hydrochloride 10mg", "Tablet", "Cipla Ltd", "Anti-allergic"),
    ("Cetzine Syrup", "Cetirizine Hydrochloride 5mg / 5ml", "Syrup", "Dr. Reddy's Laboratories", "Anti-allergic"),
    ("Wysolone 10", "Prednisolone 10mg", "Tablet", "Pfizer India", "Corticosteroid"),
    ("Predmet 10", "Prednisolone 10mg", "Tablet", "Sun Pharmaceutical", "Corticosteroid"),
    ("Chymoral Forte", "Trypsin + Chymotrypsin (100,000 Armour Units)", "Tablet", "Torrent Pharmaceuticals", "Anti-inflammatory Enzyme"),
    ("Chymocip", "Trypsin + Chymotrypsin (100,000 Armour Units)", "Tablet", "Cipla Ltd", "Anti-inflammatory Enzyme"),
    ("Deriphyllin Retard 150", "Etofylline 115mg + Theophylline 35mg SR", "Tablet", "Zydus Healthcare", "Bronchodilator"),
    ("Deriphyllin Retard 300", "Etofylline 230mg + Theophylline 70mg SR", "Tablet", "Zydus Healthcare", "Bronchodilator"),
    ("Flucan 150", "Fluconazole 150mg", "Tablet", "Lupin Ltd", "Antifungal"),
    ("Forcan 150", "Fluconazole 150mg", "Tablet", "Cipla Ltd", "Antifungal"),
    ("Emiset 4", "Ondansetron 4mg", "Tablet", "Cipla Ltd", "Antiemetic"),
    ("Odem 4", "Ondansetron 4mg", "Tablet", "Alkem Laboratories", "Antiemetic"),
    ("Emiset Syrup", "Ondansetron 2mg / 5ml", "Syrup", "Cipla Ltd", "Antiemetic"),
    ("Vigora 100", "Sildenafil Citrate 100mg", "Tablet", "Zydus Cadila", "Erectile Dysfunction"),
    ("Manforce 100", "Sildenafil Citrate 100mg", "Tablet", "Mankind Pharma", "Erectile Dysfunction"),
    ("Microfen 50", "Diclofenac Potassium 50mg", "Tablet", "Micro Labs Ltd", "Analgesic / Anti-inflammatory"),
    ("Multivite FM Omega Capsule", "Multivitamins + Minerals + Omega 3", "Capsule", "GlaxoSmithKline (GSK)", "Nutritional Supplement"),
    ("Becosules Performance Capsule", "Multivitamins + Ginseng + Minerals", "Capsule", "Pfizer India", "Nutritional Supplement"),
    ("Calamine Lotion 100ml", "Calamine 15% + Zinc Oxide 5%", "Lotion", "Piramal Pharma", "Dermatology"),
    ("Caladryl Lotion 100ml", "Calamine + Diphenhydramine Hydrochloride", "Lotion", "Piramal Pharma", "Dermatology"),
]
